### ISSUE TITLE
Godaddy Dns Problem

### ISSUE THREAD

**Issue by thinkdave1** [ngrok/ngrok#16] opened 2024-07-15 19:16 UTC
While adding a DNS record to my domain address that I purchased through Godaddy, even though I entered the correct information given by ngrok, it says the data entry is invalid and prevents me from opening a record. What is the reason?

<img width="1275" alt="348373638-f8fb1a0d-6188-48a8-8631-5549486eb2f3" src="https://github.com/user-attachments/assets/260ed83f-cc21-4b94-ac16-298f70666ebe">

**Comment by russorat** [comment] 2024-07-15 19:29
Closing as dupe of https://github.com/ngrok/ngrok/issues/14

**Closed by russorat** 2024-07-15 19:29 UTC
