### ISSUE TITLE
YAML parsing error How to fix in Kali linux / VM

### ISSUE THREAD

**Issue by Mrxmiracle** [ngrok/ngrok#40] opened 2024-09-08 20:16 UTC
Gives error after any command of ngrok
Error :------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ERROR:  Error reading configuration file '/root/.config/ngrok/ngrok.yml': YAML parsing error: yaml: unmarshal errors:
ERROR:    line 2: field authtoken not found in type config.v3yamlConfig

**Comment by davetapley** [comment] 2024-09-09 21:00
Probably dupe of:
- https://github.com/ngrok/ngrok/issues/34

**Comment by russorat** [comment] 2024-09-09 21:13
yep! 3.16 was released earlier today so you should be able to fix by upgrading.

**Closed by russorat** 2024-09-09 21:13 UTC
